# Post to {kubeApiServerAddress}/apis/frameworkcontroller.microsoft.com/v1/namespaces/default/frameworks
# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: batchstatefulfailed
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 1
  taskRoles:
    - name: worker
      taskNumber: 3
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: -1
      task:
        retryPolicy:
          fancyRetryPolicy: true
          maxRetryCount: 1
        pod:
          spec:
            restartPolicy: Never
            containers:
              - name: ubuntu
                image: ubuntu:trusty
                # To locate a specific Task during its whole lifecycle regardless of
                # any retry:
                # Consistent Identity:
                # PodName = {FrameworkName}-{TaskRoleName}-{TaskIndex}
                # PodNamespace = {FrameworkNamespace}
                # Consistent Environment Variable Value:
                # ${FRAMEWORK_NAME}, ${TASKROLE_NAME}, ${TASK_INDEX}
                # ${CONFIGMAP_NAME}, ${POD_NAME}, ${POD_NAMESPACE}
                #
                # To locate a specific execution attempt of a specific Task:
                # Attempt Specific Environment Variable Value:
                # ${FRAMEWORK_ATTEMPT_ID}, ${TASK_ATTEMPT_ID}
                #
                # To locate a specific execution attempt instance of a specific Task:
                # Attempt Instance Specific Environment Variable Value:
                # ${FRAMEWORK_ATTEMPT_INSTANCE_UID}, ${CONFIGMAP_UID}
                # ${TASK_ATTEMPT_INSTANCE_UID}, ${POD_UID}
                command: ["sh", "-c", "printenv && sleep 60 && exit 1"]
