# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: batchstatefulfailed
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 1
  taskRoles:
  - name: worker
    taskNumber: 3
    frameworkAttemptCompletionPolicy:
      minFailedTaskCount: 1
      minSucceededTaskCount: -1
    task:
      retryPolicy:
        fancyRetryPolicy: true
        maxRetryCount: 1
      pod:
        spec:
          restartPolicy: Never
          containers:
          - name: ubuntu
            image: ubuntu:trusty
            # To locate a specific Task during its whole lifecycle regardless of
            # any retry:
            # Consistent Identity:
            # PodNamespace = {FrameworkNamespace}
            # PodName = {FrameworkName}-{TaskRoleName}-{TaskIndex}
            # Consistent Environment Variable Value:
            # ${FC_FRAMEWORK_NAMESPACE},
            # ${FC_FRAMEWORK_NAME}, ${FC_TASKROLE_NAME}, ${FC_TASK_INDEX},
            # ${FC_CONFIGMAP_NAME}, ${FC_POD_NAME}
            #
            # To locate a specific execution attempt of a specific Task:
            # Attempt Specific Environment Variable Value:
            # ${FC_FRAMEWORK_ATTEMPT_ID}, ${FC_TASK_ATTEMPT_ID}
            #
            # To locate a specific execution attempt instance of a specific Task:
            # Attempt Instance Specific Environment Variable Value:
            # ${FC_FRAMEWORK_ATTEMPT_INSTANCE_UID}, ${FC_CONFIGMAP_UID}
            # ${FC_TASK_ATTEMPT_INSTANCE_UID}, ${FC_POD_UID}
            command: ["sh", "-c", "printenv && sleep 60 && exit 1"]
