# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: servicestateful
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: false
    maxRetryCount: -1
  taskRoles:
  - name: serverstateful
    taskNumber: 3
    frameworkAttemptCompletionPolicy:
      minFailedTaskCount: 1
      minSucceededTaskCount: -1
    task:
      retryPolicy:
        fancyRetryPolicy: false
        maxRetryCount: -1
      pod:
        spec:
          # Using Never restartPolicy, ActiveDeadlineSeconds and initContainers
          # just to demonstrate consistent identities in this example.
          restartPolicy: Never
          ActiveDeadlineSeconds: 60
          containers:
          - name: nginx
            image: nginx:stable
            ports:
            - containerPort: 80
          initContainers:
          - name: ubuntu
            image: ubuntu:trusty
            # See comments in batchstatefulfailed.yaml
            command: ["sh", "-c", "printenv"]
---
# Post to {kubeApiServerAddress}/api/v1/namespaces/default/services/
apiVersion: v1
kind: Service
metadata:
  name: serverstateful
spec:
  selector:
    # See comments in service.yaml
    FC_FRAMEWORK_NAME: servicestateful
    FC_TASKROLE_NAME: serverstateful
  ports:
  - port: 80
  type: NodePort
