// MIT License
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/microsoft/frameworkcontroller/pkg/apis/frameworkcontroller/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FrameworkLister helps list Frameworks.
type FrameworkLister interface {
	// List lists all Frameworks in the indexer.
	List(selector labels.Selector) (ret []*v1.Framework, err error)
	// Frameworks returns an object that can list and get Frameworks.
	Frameworks(namespace string) FrameworkNamespaceLister
	FrameworkListerExpansion
}

// frameworkLister implements the FrameworkLister interface.
type frameworkLister struct {
	indexer cache.Indexer
}

// NewFrameworkLister returns a new FrameworkLister.
func NewFrameworkLister(indexer cache.Indexer) FrameworkLister {
	return &frameworkLister{indexer: indexer}
}

// List lists all Frameworks in the indexer.
func (s *frameworkLister) List(selector labels.Selector) (ret []*v1.Framework, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Framework))
	})
	return ret, err
}

// Frameworks returns an object that can list and get Frameworks.
func (s *frameworkLister) Frameworks(namespace string) FrameworkNamespaceLister {
	return frameworkNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FrameworkNamespaceLister helps list and get Frameworks.
type FrameworkNamespaceLister interface {
	// List lists all Frameworks in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.Framework, err error)
	// Get retrieves the Framework from the indexer for a given namespace and name.
	Get(name string) (*v1.Framework, error)
	FrameworkNamespaceListerExpansion
}

// frameworkNamespaceLister implements the FrameworkNamespaceLister
// interface.
type frameworkNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Frameworks in the indexer for a given namespace.
func (s frameworkNamespaceLister) List(selector labels.Selector) (ret []*v1.Framework, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Framework))
	})
	return ret, err
}

// Get retrieves the Framework from the indexer for a given namespace and name.
func (s frameworkNamespaceLister) Get(name string) (*v1.Framework, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("framework"), name)
	}
	return obj.(*v1.Framework), nil
}
