/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	frameworkcontrollerv1 "github.com/microsoft/frameworkcontroller/pkg/apis/frameworkcontroller/v1"
	versioned "github.com/microsoft/frameworkcontroller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/microsoft/frameworkcontroller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/microsoft/frameworkcontroller/pkg/client/listers/frameworkcontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FrameworkInformer provides access to a shared informer and lister for
// Frameworks.
type FrameworkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FrameworkLister
}

type frameworkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFrameworkInformer constructs a new informer for Framework type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFrameworkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFrameworkInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFrameworkInformer constructs a new informer for Framework type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFrameworkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FrameworkcontrollerV1().Frameworks(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FrameworkcontrollerV1().Frameworks(namespace).Watch(options)
			},
		},
		&frameworkcontrollerv1.Framework{},
		resyncPeriod,
		indexers,
	)
}

func (f *frameworkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFrameworkInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *frameworkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&frameworkcontrollerv1.Framework{}, f.defaultInformer)
}

func (f *frameworkInformer) Lister() v1.FrameworkLister {
	return v1.NewFrameworkLister(f.Informer().GetIndexer())
}
