name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  frameworkcontroller:
    name: frameworkcontroller
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: build/frameworkcontroller/docker-build.sh

  frameworkbarrier:
    name: frameworkbarrier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: build/frameworkbarrier/docker-build.sh
